//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public System.Guid ProductID { get; set; }
        public System.Guid UserTypeID { get; set; }
        public double Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
